//! Known-answer tests.
//!
//! `kat.json` was generated by running the specification's own reference
//! Python, extracted from the draft, so these vectors check this crate against
//! the document rather than against itself.

use serde_json::Value;
use shrincs::{keygen, params::*, sign, verify, Structure};

fn hex(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
        .collect()
}

fn kat() -> Value {
    serde_json::from_str(include_str!("kat.json")).unwrap()
}

#[test]
fn parameters_match_the_draft() {
    shrincs::verify_parameter_consistency().unwrap();
}

#[test]
fn components_match_the_reference() {
    let k = kat();
    let c = &k["components"];
    let seed = hex(k["seed"].as_str().unwrap());
    let pk_seed = &seed[32..48];
    let digest = hex(c["grind_digest"].as_str().unwrap());

    let mut adrs = shrincs::adrs::Adrs::new();
    let (counter, indexes) =
        shrincs::wots::wots_c_grind::<shrincs::hash::Sha256>(pk_seed, &digest, &mut adrs).unwrap();
    assert_eq!(
        counter as u64,
        c["grind_counter"].as_u64().unwrap(),
        "grinding counter"
    );
    let want: Vec<u32> = c["grind_indexes"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_u64().unwrap() as u32)
        .collect();
    assert_eq!(indexes, want, "chain indexes");
    assert_eq!(indexes.iter().sum::<u32>() as usize, WOTS_C_CONSTANT_SUM);
}

#[test]
fn keys_and_signatures_match_the_reference() {
    let k = kat();
    let seed: [u8; 48] = hex(k["seed"].as_str().unwrap()).try_into().unwrap();

    for case in k["cases"].as_array().unwrap() {
        let sf = hex(case["sf_structure"].as_str().unwrap());
        let structure = Structure([sf[0], sf[1]]);
        let (sk, pk) = keygen(&seed, structure);
        assert_eq!(
            sk.to_vec(),
            hex(case["seckey"].as_str().unwrap()),
            "secret key"
        );
        assert_eq!(
            pk.to_vec(),
            hex(case["pubkey"].as_str().unwrap()),
            "public key"
        );

        for s in case["stateful"].as_array().unwrap() {
            let ctr = s["ctr"].as_u64().unwrap();
            let msg = hex(s["msg"].as_str().unwrap());
            let want = hex(s["sig"].as_str().unwrap());
            let got = sign(&msg, b"", &sk, Some(ctr), None).expect("stateful sign");
            assert_eq!(got, want, "stateful signature at ctr {ctr}");
            assert!(verify(&msg, &got, b"", &pk), "own signature must verify");
        }

        let sl = &case["stateless"];
        let msg = hex(sl["msg"].as_str().unwrap());
        let want = hex(sl["sig"].as_str().unwrap());
        let got = sign(&msg, b"", &sk, None, None).expect("stateless sign");
        assert_eq!(got, want, "stateless signature");
        assert_eq!(got.len(), SL_SIGNATURE_SIZE);
        assert!(verify(&msg, &got, b"", &pk));
    }
}

#[test]
fn budget_exhaustion_falls_back_rather_than_failing() {
    let seed = [3u8; 48];
    let structure = Structure::unbalanced(4);
    let (sk, pk) = keygen(&seed, structure);
    for c in 0..structure.budget() {
        let s = sign(b"m", b"", &sk, Some(c), None).unwrap();
        assert!(
            s.len() < SL_SIGNATURE_SIZE,
            "within budget the stateful path signs"
        );
        assert!(verify(b"m", &s, b"", &pk));
    }
    let past = sign(b"m", b"", &sk, Some(structure.budget()), None).unwrap();
    assert_eq!(
        past.len(),
        SL_SIGNATURE_SIZE,
        "past the budget, the fallback signs"
    );
    assert!(verify(b"m", &past, b"", &pk));
}

#[test]
fn signature_sizes_follow_the_size_law() {
    let seed = [5u8; 48];
    let (sk, _) = keygen(&seed, Structure::unbalanced(6));
    for c in 0..7u64 {
        let d = (c + 1).min(6) as usize;
        let want = 1 + N + d.min(64).div_ceil(8) + 2 + WOTS_C_CHAINS_SIZE + d * N;
        assert_eq!(
            sign(b"m", b"", &sk, Some(c), None).unwrap().len(),
            want,
            "depth {d}"
        );
    }
}

#[test]
fn tampering_is_rejected() {
    let seed = [9u8; 48];
    let (sk, pk) = keygen(&seed, Structure::balanced(2));
    for state in [Some(0u64), None] {
        let sig = sign(b"authentic", b"", &sk, state, None).unwrap();
        assert!(verify(b"authentic", &sig, b"", &pk));
        assert!(!verify(b"forged", &sig, b"", &pk), "message swap");
        assert!(!verify(b"authentic", &sig, b"ctx", &pk), "context swap");
        for i in [0usize, 1, sig.len() / 2, sig.len() - 1] {
            let mut bad = sig.clone();
            bad[i] ^= 1;
            assert!(
                !verify(b"authentic", &bad, b"", &pk),
                "flipped bit in byte {i}"
            );
        }
        let (_, other_pk) = keygen(&[10u8; 48], Structure::balanced(2));
        assert!(!verify(b"authentic", &sig, b"", &other_pk), "wrong key");
    }
}
